# GovOS Milestone M7: Fast Parallel E2E SLA Watchdog & Escalation Engine Verification
$ErrorActionPreference = "Stop"

Write-Host "`n========================================================" -ForegroundColor Cyan
Write-Host "  GovOS Phase 1: M7 SLA Watchdog & Escalation Engine    " -ForegroundColor Cyan
Write-Host "========================================================`n" -ForegroundColor Cyan

# 1. Health & Policy Check
Write-Host "[1/5] Verifying SLA Policy Configuration in PostgreSQL..." -ForegroundColor Yellow
$policies = docker exec -i govos-postgres psql -U govos_user -d govos_db -c "
SELECT category, priority, resolution_hours, warning_threshold_ratio, escalation_level_1_hours, escalation_level_2_hours
FROM sla_policies
ORDER BY priority, category;
"
Write-Host "$policies" -ForegroundColor Green

# 2. Function to submit a complaint
function Submit-TestComplaint([string]$title, [string]$desc) {
    $p = @{
        name = "SLA Test Citizen"
        mobile = "9876543210"
        title = $title
        description = $desc
        latitude = 15.3647
        longitude = 75.1240
        locationAddress = "Sirur Park Market, Ward 42"
        subCategory = "Waste Collection"
    } | ConvertTo-Json

    $tempFile = "$PSScriptRoot\temp_sub.json"
    $p | Out-File -FilePath $tempFile -Encoding utf8
    $res = curl.exe -s -X POST http://localhost:8080/api/v1/public/complaints -H "Content-Type: application/json" --data-binary "@$tempFile"
    $json = $res | ConvertFrom-Json
    return $json.complaintNumber
}

Write-Host "`n[2/5] Creating 4 test complaints for concurrent SLA evaluation..." -ForegroundColor Yellow
$c1 = Submit-TestComplaint "SLA Warning Test" "Testing 75% warning trigger"
$c2 = Submit-TestComplaint "SLA Breach L1 Test" "Testing Level 1 breach escalation"
$c3 = Submit-TestComplaint "SLA Escalation L2 Test" "Testing Level 2 severe escalation"
$c4 = Submit-TestComplaint "SLA Auto-Close Test" "Testing 72h auto close on resolved tickets"

Write-Host "  -> C1 (Warning): $c1" -ForegroundColor Cyan
Write-Host "  -> C2 (Breach L1): $c2" -ForegroundColor Cyan
Write-Host "  -> C3 (Escalate L2): $c3" -ForegroundColor Cyan
Write-Host "  -> C4 (Auto-Close): $c4" -ForegroundColor Cyan

# 3. Setup test scenarios in DB
Write-Host "`n[3/5] Setting up target timestamps in PostgreSQL..." -ForegroundColor Yellow

# Scenario 1: Warning condition (80% elapsed for 48h SLA)
docker exec -i govos-postgres psql -U govos_user -d govos_db -c "
UPDATE complaints 
SET created_at = NOW() - INTERVAL '40 hours',
    sla_deadline = NOW() + INTERVAL '8 hours',
    sla_warning_sent = false,
    sla_breached = false
WHERE complaint_number = '$c1';
"

# Scenario 2: Initial breach (deadline expired 2 hours ago)
docker exec -i govos-postgres psql -U govos_user -d govos_db -c "
UPDATE complaints 
SET sla_deadline = NOW() - INTERVAL '2 hours',
    sla_breached = false,
    escalation_level = 0
WHERE complaint_number = '$c2';
"

# Scenario 3: Level 2 Severe Escalation (deadline expired 26 hours ago, L1 already breached)
docker exec -i govos-postgres psql -U govos_user -d govos_db -c "
UPDATE complaints 
SET sla_deadline = NOW() - INTERVAL '26 hours',
    sla_breached = true,
    escalation_level = 1,
    priority = 'MEDIUM'
WHERE complaint_number = '$c3';
"

# Scenario 4: Auto-close after 72 hours in RESOLVED state
docker exec -i govos-postgres psql -U govos_user -d govos_db -c "
UPDATE complaints 
SET status = 'RESOLVED',
    resolved_at = NOW() - INTERVAL '75 hours'
WHERE complaint_number = '$c4';
"

Write-Host "  -> Scenarios primed in DB. Waiting 62s for single scheduled SlaScheduler watchdog run..." -ForegroundColor Yellow
Start-Sleep -Seconds 62

# 4. Verify Database states
Write-Host "`n[4/5] Verifying Post-Watchdog Complaint States..." -ForegroundColor Yellow
$results = docker exec -i govos-postgres psql -U govos_user -d govos_db -c "
SELECT complaint_number, status, priority, sla_warning_sent, sla_breached, escalation_level
FROM complaints
WHERE complaint_number IN ('$c1', '$c2', '$c3', '$c4')
ORDER BY complaint_number;
"
Write-Host "$results" -ForegroundColor Green

# 5. Verify Outbox Events
Write-Host "`n[5/5] Verifying Outbox Events generated by SLA Engine..." -ForegroundColor Yellow
$outboxResults = docker exec -i govos-postgres psql -U govos_user -d govos_db -c "
SELECT event_type, status, retry_count, payload->>'complaintNumber' AS complaint_number
FROM outbox_events
WHERE payload->>'complaintNumber' IN ('$c1', '$c2', '$c3', '$c4')
ORDER BY created_at ASC;
"
Write-Host "$outboxResults" -ForegroundColor Green

Write-Host "`n✅ MILESTONE M7 E2E VERIFICATION COMPLETED SUCCESSFULLY!`n" -ForegroundColor Green
